- npm2deb/templates.py
> Set priority in debian/control to default to optional

- npm2deb/__init__.py
This is fixing Lintian vcs-field-uses-insecure-uri error
> Change Vcs-* URLs to https

- npm2deb/mapper.py
Fixes https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=836182
> Use rmadison to find available packages

- npm2deb/__init__.py
- npm2deb/mapper.py
- npm2deb/utils.py
Fixes https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=840226
Debianize modules names before searching for debian packages
> Convert package name to lowercase

- npm2deb/__init__.py
Fixes https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=840169
> Handle invalid repository field

- npm2deb/__init__.py
bump standards version of generated packages to 3.9.8
> bump standards version

- npm2deb/__init__.py
This should fix [https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=840207](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=840207)
> converting dependency package name format

- npm2deb/__init__.py
https://docs.npmjs.com/files/package.json#directories
https://docs.npmjs.com/files/package.json#files
Fixes https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=841995
> Install files from directories and files fields

- npm2deb/__init__.py
Avoids the overhead of downloading/installing dependencies
caused by `npm install`
> Use npm pack to download module files

- Changelog.md
- npm2deb/__init__.py
> Release 0.2.6

- npm2deb/__init__.py
Fixes https://github.com/LeoIannacone/npm2deb/issues/20
> Check man field is not an array

- npm2deb/helper.py
I have changed helper.py in such a way that it fixes the bug:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=852775
> npm2deb searches in debian experimental branch for availability of packages.

- npm2deb/__init__.py
> Normalize and sanitize install filepaths

- npm2deb/__init__.py
- npm2deb/templates.py
so it gives a hint that more work may be required to write a good description
> update description template

- npm2deb/helper.py
> Use debian-name in repo and bug searches

- npm2deb/scripts.py
- npm2deb/utils.py
> Abort execution in non-utf environments

- .gitignore
> Add build files to .gitignore

- npm2deb/templates.py
section javascript is now created in the archive for nodejs/javascript packages
> change section to javascript

- npm2deb/mapper.py
take the last result of rmadison for latest version (currently it takes the oldest version in result). Fixes #86.
> take the last result of rmadison

- npm2deb/templates.py
licensecheck tool outputs in this format (cme update dpkg-copyright command also does this)
> update copyright line formatting

- npm2deb/templates.py
Updated urls from http to https in templates.py file.
> converted http to https

- npm2deb/helper.py
the function now first searches on salsa - only if no repo is found there it proceeds to also search on anonscm
TODO: the returned data structure does not carry information whether the repo was found on salsa or on anonscm; the consumer in `npm2deb/scripts.py` should be changed too if we also want to show / report that.
> #97: also update search_for_repository function

- Changelog.md
- npm2deb/__init__.py
Update changelog and npm2deb version :)
> Release 0.2.7

- npm2deb/helper.py
Since, alioth is recently shut down, We should stop searching on anonscm
> Avoid searching on anonscm(Fixes #106)

- npm2deb/__init__.py
- npm2deb/helper.py
- npm2deb/mapper.py
- npm2deb/scripts.py
- npm2deb/utils.py
- setup.py
- tests/tests.py
Fixes #94 
Also resolves the issues in pr#96
>  Fix failure when creating @types/<name> modules 

- npm2deb/__init__.py
Switch vcs url from old anonscm.d.o to new salsa.d.o
> Switch vcs urls to salsa

- npm2deb/__init__.py
- npm2deb/mapper.py
- npm2deb/scripts.py
- npm2deb/utils.py
> Always take latest standards version dynamically

- npm2deb/__init__.py
- npm2deb/helper.py
> Updating the endpoint which retrieves reverse dependencies.

- npm2deb/utils.py
- tests/tests.py
> npm version bug fix

- npm2deb/__init__.py
- npm2deb/templates.py
- npm2deb/utils.py
Hi,
some improvements:
* update S-V
* use pkg-js-tools for tests/autopkgtest
* optimize debian/watch
> Improvements

- npm2deb/__init__.py
- npm2deb/templates.py
- npm2deb/utils.py
may be incomplete. Fixes: #135
> add gitlab.com support

- npm2deb/__init__.py
- npm2deb/templates.py
- tests/tests.py
I think it's time to delete old debian/compat file
> Switch to debhelper-compat

- npm2deb/__init__.py
- npm2deb/templates.py
> 84 cleanup temporary directory

- npm2deb/__init__.py
> automate import-dsc command
